# By yushi4ka
# v1.2.0

# Download: PlaceholderAPI and LuckPerms
# For PlaceholderAPI: /papi ecloud download LuckPerms
# Using: § nd &
# Plugin Placeholder: %name% and %message%

global-chat: true
global-chat-syntax: '!'

local-chat-radius: 25

chat-display:
  enable: false
  expiration-time: 5
  format: "§f%message%"

Messages:
  tag: "[&#E43A96S&#E64A9Ea&#E759A6k&#E969AEu&#EA78B6r&#EC88BEa&#ED97C6C&#EFA7CEh&#F0B6D6a&#F2C6DEt&f] "
  no-permission: "§c§l× §cУвас не достаточно прав!"
  cmd-reload-message: "§aКонфигурация плагина была перезагружена!"
  global-chat-disabled: "§c§l× §cГлобальный чат выключен!"
  no-players-nearby: "§c§l× §cВас никто не услышал."
Chat-Messages:
  local-chat-format: '§eL §r%luckperms_prefix%§r%name%§r%luckperms_suffix%§r: §7%message%'
  global-chat-format: '§aG §r%luckperms_prefix%§r%name%§r%luckperms_suffix%§r: §e%message%'
JoinQuit-Messages:
  Join-message: "§a§l→ §r%name%§a присоединился к серверу."
  Quit-message: "§c§l← §r%name%§c покинул сервер."
