# By yushi4ka
# v1.2.5

# Download: PlaceholderAPI and LuckPerms
# For PlaceholderAPI: /papi ecloud download LuckPerms

lang: en.yml

global-chat: true
global-chat-syntax: '!'

local-chat-radius: 25

chat-display:
  enable: false
  expiration-time: 5
  format: "§f%message%"
