name: SakuraChat
version: ${project.version}
main: org.winterdev.SakuraChat.SakuraChat
api-version: '1.21'
authors: [ yushi4ka ]
description: Minecraft plugin
depend:
  - LuckPerms
  - PlaceholderAPI
commands:
  schat:
    description: Plugin commands
    permission: sakurachat.admin
